### ISSUE TITLE
Implement initial shoot subsystem

### ISSUE THREAD

**Issue by joefrayne** [MDHSRobotics/StarBot#4]
Uses encoders and a feedback loop to maintain a specified RPM. Moves at the same time as the conveyor.
4 redline motors

Shooting:
Be able to maintain RPM (using encoders).
Assuming 45 degree launch angle, and the robot is 11' from the target, the initial velocity should be 27 ft/s.

**Comment by joefrayne** [comment]
Need to add John Castillo as an assignee.

**Comment by JackMRobotics** [comment]
Josh C. is working on the climb with Megan
